update Dockerfile with ubuntu:24.04
This updates the Dockerfile to use ubuntu:24.04 and other necessary changes:

jbig2 is installed to fix

> The program 'jbig2' could not be executed or was not found on your
> system PATH.  This program is recommended when using the --optimize {2,3} | --jbig2-lossy arguments,
> but not required, so we will proceed.  For best results, install the program.

tesseract-ocr-deu is installed to fix

> ocrmypdf.exceptions.MissingDependencyError: OCR engine does not have language data for the following requested languages:
> deu
> Please install the appropriate language data for your OCR engine.

--break-system-packages is set to allow to install into the system environment, otherwise pip exits with an error.
In this case, this is okay, since we don't care about the system python.